### ISSUE TITLE
toString methods on chunks

### ISSUE THREAD

**Issue by IgnacioRondini** [AxoKoi/BlogCode#4]
We need to add a toString method to the Chunk class and every subclass, so we can have debug information.

**Comment by danindugit** [comment]
Working on adding toString methods to the Chunk Class and its subclasses.

**Comment by IgnacioRondini** [comment]
Hello Dadindugit,
Thanks for get interested in the project! You can check the current class diagram on the wiki or visit the series in the axokoi blog: http://axokoi.com/index.php/2020/05/11/creando-un-png-parte-1/ 
It's written in spanish but the translate option works quite well :)

As for this issue, I was thinking to have a common toString in the abstract Chunk class and a complementary on the sub classes (at least on the one that are already implemented). If you have any doubts, don't hesitate!

**Comment by danindugit** [comment]
I have added toString methods for the Chunk class and all of its subclasses. The IDATChunk and IENDChunk classes have no fields or methods of their own, so I included the inherited methods and fields in their toString methods. As for the Chunk, IHDRChunk, and PLTEChunk classes, I included only the fields and methods that existed in that class in their respective toString methods.  

I will submit a pull request. If you have any concerns or other changes to be made, please let me know.

**Comment by danindugit** [comment]
(I also indented all the files I made changes on)

**Comment by IgnacioRondini** [comment]
Hi, I put the comments on the pull request :)

**Comment by danindugit** [comment]
Hi, I made the changes that you asked for. Let me know if you need anything else :)

**Comment by IgnacioRondini** [comment]
It seems ok for me, I just added small comment.
Also, do you think it would be possible to not change the format/indentation? otherwise I'll  do it myself. :)

**Comment by danindugit** [comment]
Yup! I have restored your original indentation and made the change that you requested. I committed and pushed those changes. :)

**Comment by IgnacioRondini** [comment]
I've merged your pull request :) 
Thanks for collaborating!
ps: From now on, each Chunk should implement its own toString() , as commented in the corresponding issue #2

**Comment by danindugit** [comment]
Thank you for this opportunity :)

**Comment by IgnacioRondini** [comment]
Of course, the project is still begining, so there is a lot to do yet :). Probably at some moment it's going to be a repository by itself, so don't hesitate if you want to keep involved. Have a nice week end!

**Comment by danindugit** [comment]
Sound good! I'll stay tuned. All the best :)
